[build]
target = "index.html"
public_url = "/WebResume/"

[serve]
port = 8085

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp dist/.stage/index.html dist/.stage/404.html"]

